// Auto-generated configuration file for conv testbench
// Generated by gen_conv.py

localparam int unsigned P_ICH = 4;
localparam int unsigned P_OCH = 2;
localparam int unsigned N_ICH = 8;
localparam int unsigned N_OCH = 4;
localparam int unsigned K = 3;
localparam int unsigned A_BIT = 8;
localparam int unsigned W_BIT = 8;
localparam int unsigned B_BIT = 32;
localparam int unsigned N_HW = 20;

// Im2col parameters
localparam int unsigned N_IH = 5;
localparam int unsigned N_IW = 5;
localparam int unsigned STRIDE = 1;
localparam int unsigned PAD = 1;

// Derived parameters
localparam int unsigned FOLD_I = N_ICH / P_ICH;
localparam int unsigned FOLD_O = N_OCH / P_OCH;
localparam int unsigned KK = K * K;
localparam int unsigned WEIGHT_DEPTH = FOLD_O * FOLD_I * KK;
