// Auto-generated configuration file for deconv testbench
// Generated by gen_deconv.py

localparam int unsigned P_ICH = 4;
localparam int unsigned P_OCH = 2;
localparam int unsigned N_ICH = 8;
localparam int unsigned N_OCH = 4;
localparam int unsigned K = 3;
localparam int unsigned Z_NUM = 8;
localparam int unsigned A_BIT = 8;
localparam int unsigned W_BIT = 8;
localparam int unsigned B_BIT = 32;
localparam int unsigned STRIDE = 2;
localparam int unsigned PADDING = 1;
localparam int unsigned OUTPUT_PADDING = 0;
localparam int unsigned IN_H = 5;
localparam int unsigned IN_W = 5;
localparam int unsigned OUT_H = 9;
localparam int unsigned OUT_W = 9;

// Derived parameters
localparam int unsigned FOLD_I = N_ICH / P_ICH;
localparam int unsigned FOLD_O = N_OCH / P_OCH;
localparam int unsigned KK = K * K;
localparam int unsigned WEIGHT_DEPTH = FOLD_O * FOLD_I * KK;
localparam int unsigned IN_HW = IN_H * IN_W;
localparam int unsigned OUT_HW = OUT_H * OUT_W;
