// Auto-generated configuration file for maxpool testbench
// Generated by gen_maxpool.py

localparam int unsigned P_CH = 4;
localparam int unsigned N_CH = 32;
localparam int unsigned N_IH = 40;
localparam int unsigned N_IW = 80;
localparam int unsigned N_OH = 20;
localparam int unsigned N_OW = 40;
localparam int unsigned A_BIT = 8;
localparam int unsigned STRIDE = 2;
localparam int unsigned KERNEL = 2;

// Derived parameters
localparam int unsigned FOLD = N_CH / P_CH;
localparam int unsigned INPUT_SIZE = N_IH * N_IW * FOLD;
localparam int unsigned OUTPUT_SIZE = N_OH * N_OW * FOLD;
